export const GET_ITEM_QUANTITY = 'CART/GET_ITEM_QUANTITY';
export const REMOVE_TO_CART = 'CART/REMOVE_TO_CART';
export const INCREASE_QUANTITY = 'CART/INCREASE_QUANTITY'
export const DECREASE_QUANTITY = 'CART/DECRESE_QUANTITY'